In [2]:
# Importing libraries

# solver.py has: 
# the solver (Checks if a puzzle is valid and resolve te sudoku using all the techniques)
# Solve by technique (Checks if a puzzle can be solved just using a specific technique)
from solver import *

# ai.py has inside all the techniques, validator and trackers necessary to solvve a puzzle 
from ai import *
import pandas as pd
import numpy as np

### Scenarios
Those are different escenarios than have a Sudoku puzzle:

In [3]:
# Test1: (Return a state 2 in our Solver.py) The puzzle is invalid and the same number in a row or column. 
test1 = '88..74...1.........7.5.9.4....65.4..73.....296.8.......2.3.1.5.........8...9....2'

# Test3 2 and 3: (Return a state 1 in our Solver.py) Those are valid puzzles
test2 = '.5.....7.9......6...21.75.8.4..69.3...8...4...3.42..5.3.12.86...9......1.8.....2.'
test3 = '8...74...1.........7.5.9.4....65.4..73.....296.8.......2.3.1.5.........8...9....2'

# Test 4:(Return a state 3 in our Solver.py) Valid Sudoku, the initial puzzle follows the Sudoku rules
# but doesn't have a solution
test4 = '...2....58....9..4...18..2.3.....5.95......7..6.....4.........6..1.3498.92.85...3'

# Test_triple 1,2 and . Those are puzzle that have naked triples (sudoku technique)
test_triple = '...29438....17864.48.3561....48375.1...4157..5..629834953782416126543978.4.961253'
test_triple2 = '4..5..37.32......4.........8....2.3.21.84...........9..7..9.1..94.651.......7....'
test_triple3 = '39....7........65.5.7...349.4938.5.66.1.54983853...4..9..8..134..294.8654.....297'

names_tests = ['test2', 'test3', 'test4', 'test_triple', 'test_triple2', 'test_triple3']
tests = [test2, test3, test4, test_triple, test_triple2, test_triple3]

## Testing all the possible scenarios 
##### Except when the puzzle is invalid in the beginning (doesn't follow the Sudoku rules) after loading the image

In [4]:
"""
To solve a puzzle use the function solve and pass the sudoku grid( String 81 characters)
"""
count=0
for test in tests:
    print(names_tests[count] + ' :' + "\n", solve(test)[0])
    count+=1

test2 :
 1
test3 :
 1
test4 :
 3
test_triple :
 1
test_triple2 :
 1
test_triple3 :
 1

In [5]:
solve(test1)

(2,
 [['8', 'A1'], ['8', 'A2']],
 '88..74...1.........7.5.9.4....65.4..73.....296.8.......2.3.1.5.........8...9....2',
 'No Difficulty Level')

In [23]:
count=0
for test in tests:
    print(names_tests[count])
    grid = dict(zip(boxes, ["." if
                    element == "." else element for element in test]))
    count += 1
    state = solve(test)[0]
    print('State: ', state)
    print('Initial Grid')
    #display a puzzle in a grid
    display(grid)
    if state == 1:
        print('Solution')
        display(conv_values(solve(test)[1]))

test2
State:  1
Initial Grid
. 5 . |. . . |. 7 .
9 . . |. . . |. 6 .
. . 2 |1 . 7 |5 . 8
------+------+------
. 4 . |. 6 9 |. 3 .
. . 8 |. . . |4 . .
. 3 . |4 2 . |. 5 .
------+------+------
3 . 1 |2 . 8 |6 . .
. 9 . |. . . |. . 1
. 8 . |. . . |. 2 .

Solution
8 5 3 |9 4 6 |1 7 2
9 1 7 |5 8 2 |3 6 4
4 6 2 |1 3 7 |5 9 8
------+------+------
1 4 5 |8 6 9 |2 3 7
6 2 8 |3 7 5 |4 1 9
7 3 9 |4 2 1 |8 5 6
------+------+------
3 7 1 |2 9 8 |6 4 5
2 9 4 |6 5 3 |7 8 1
5 8 6 |7 1 4 |9 2 3

test3
State:  1
Initial Grid
8 . . |. 7 4 |. . .
1 . . |. . . |. . .
. 7 . |5 . 9 |. 4 .
------+------+------
. . . |6 5 . |4 . .
7 3 . |. . . |. 2 9
6 . 8 |. . . |. . .
------+------+------
. 2 . |3 . 1 |. 5 .
. . . |. . . |. . 8
. . . |9 . . |. . 2

Solution
8 5 9 |1 7 4 |2 3 6
1 6 4 |8 3 2 |5 9 7
3 7 2 |5 6 9 |8 4 1
------+------+------
2 9 1 |6 5 7 |4 8 3
7 3 5 |4 1 8 |6 2 9
6 4 8 |2 9 3 |1 7 5
------+------+------
9 2 6 |3 8 1 |7 5 4
4 1 3 |7 2 5 |9 6 8
5 8 7 |9 4 6 |3 1 2

test4
State:  3
Initial Grid
. . . |2 . . |. . 5
8 . . |. . 9 |. . 4
. . . |1 8 . |. 2 .
------+------+------
3 . . |. . . |5 . 9
5 . . |. . . |. 7 .
. 6 . |. . . |. 4 .
------+------+------
. . . |. . . |. . 6
. . 1 |. 3 4 |9 8 .
9 2 . |8 5 . |. . 3

test_triple
State:  1
Initial Grid
. . . |2 9 4 |3 8 .
. . . |1 7 8 |6 4 .
4 8 . |3 5 6 |1 . .
------+------+------
. . 4 |8 3 7 |5 . 1
. . . |4 1 5 |7 . .
5 . . |6 2 9 |8 3 4
------+------+------
9 5 3 |7 8 2 |4 1 6
1 2 6 |5 4 3 |9 7 8
. 4 . |9 6 1 |2 5 3

Solution
6 1 5 |2 9 4 |3 8 7
3 9 2 |1 7 8 |6 4 5
4 8 7 |3 5 6 |1 2 9
------+------+------
2 6 4 |8 3 7 |5 9 1
8 3 9 |4 1 5 |7 6 2
5 7 1 |6 2 9 |8 3 4
------+------+------
9 5 3 |7 8 2 |4 1 6
1 2 6 |5 4 3 |9 7 8
7 4 8 |9 6 1 |2 5 3

test_triple2
State:  1
Initial Grid
4 . . |5 . . |3 7 .
3 2 . |. . . |. . 4
. . . |. . . |. . .
------+------+------
8 . . |. . 2 |. 3 .
2 1 . |8 4 . |. . .
. . . |. . . |. 9 .
------+------+------
. 7 . |. 9 . |1 . .
9 4 . |6 5 1 |. . .
. . . |. 7 . |. . .

Solution
4 8 1 |5 2 6 |3 7 9
3 2 5 |9 1 7 |6 8 4
6 9 7 |3 8 4 |2 1 5
------+------+------
8 5 9 |7 6 2 |4 3 1
2 1 3 |8 4 9 |5 6 7
7 6 4 |1 3 5 |8 9 2
------+------+------
5 7 6 |2 9 3 |1 4 8
9 4 8 |6 5 1 |7 2 3
1 3 2 |4 7 8 |9 5 6

test_triple3
State:  1
Initial Grid
3 9 . |. . . |7 . .
. . . |. . . |6 5 .
5 . 7 |. . . |3 4 9
------+------+------
. 4 9 |3 8 . |5 . 6
6 . 1 |. 5 4 |9 8 3
8 5 3 |. . . |4 . .
------+------+------
9 . . |8 . . |1 3 4
. . 2 |9 4 . |8 6 5
4 . . |. . . |2 9 7

Solution
3 9 6 |4 2 5 |7 1 8
1 8 4 |7 3 9 |6 5 2
5 2 7 |1 6 8 |3 4 9
------+------+------
2 4 9 |3 8 1 |5 7 6
6 7 1 |2 5 4 |9 8 3
8 5 3 |6 9 7 |4 2 1
------+------+------
9 6 5 |8 7 2 |1 3 4
7 1 2 |9 4 3 |8 6 5
4 3 8 |5 1 6 |2 9 7

### Testing scenario when the puzzle is invalid from the beginning (doesn't follow the Sudoku rules) after loading the image

In [26]:
print(solve(test1))
print('\n Initial Grid: ')
display(dict(zip(boxes, ["." if
                    element == "." else element for element in test1])))

(2, [['8', 'A1'], ['8', 'A2']], '88..74...1.........7.5.9.4....65.4..73.....296.8.......2.3.1.5.........8...9....2', 'No Difficulty Level')

 Initial Grid:
8 8 . |. 7 4 |. . .
1 . . |. . . |. . .
. 7 . |5 . 9 |. 4 .
------+------+------
. . . |6 5 . |4 . .
7 3 . |. . . |. 2 9
6 . 8 |. . . |. . .
------+------+------
. 2 . |3 . 1 |. 5 .
. . . |. . . |. . 8
. . . |9 . . |. . 2

### Individual Testing

In [27]:
test_individual = tests[3]
# convert a string into the dictionary with the values
grid_test_individual = dict(zip(boxes, ["123456789" if element == "." else element for element in test_individual]))
len(test_individual)

81

In [28]:
solve(test_individual)

(1,
 '615294387392178645487356129264837591839415762571629834953782416126543978748961253',
 '...29438....17864.48.3561....48375.1...4157..5..629834953782416126543978.4.961253',
 'Diabolical')

In [29]:
#search( ) is the function try to reduce a puzzle as much as possible and returns the solution
search(grid_test_individual)

{'A1': '6',
 'A2': '1',
 'A3': '5',
 'A4': '2',
 'A5': '9',
 'A6': '4',
 'A7': '3',
 'A8': '8',
 'A9': '7',
 'B1': '3',
 'B2': '9',
 'B3': '2',
 'B4': '1',
 'B5': '7',
 'B6': '8',
 'B7': '6',
 'B8': '4',
 'B9': '5',
 'C1': '4',
 'C2': '8',
 'C3': '7',
 'C4': '3',
 'C5': '5',
 'C6': '6',
 'C7': '1',
 'C8': '2',
 'C9': '9',
 'D1': '2',
 'D2': '6',
 'D3': '4',
 'D4': '8',
 'D5': '3',
 'D6': '7',
 'D7': '5',
 'D8': '9',
 'D9': '1',
 'E1': '8',
 'E2': '3',
 'E3': '9',
 'E4': '4',
 'E5': '1',
 'E6': '5',
 'E7': '7',
 'E8': '6',
 'E9': '2',
 'F1': '5',
 'F2': '7',
 'F3': '1',
 'F4': '6',
 'F5': '2',
 'F6': '9',
 'F7': '8',
 'F8': '3',
 'F9': '4',
 'G1': '9',
 'G2': '5',
 'G3': '3',
 'G4': '7',
 'G5': '8',
 'G6': '2',
 'G7': '4',
 'G8': '1',
 'G9': '6',
 'H1': '1',
 'H2': '2',
 'H3': '6',
 'H4': '5',
 'H5': '4',
 'H6': '3',
 'H7': '9',
 'H8': '7',
 'H9': '8',
 'I1': '7',
 'I2': '4',
 'I3': '8',
 'I4': '9',
 'I5': '6',
 'I6': '1',
 'I7': '2',
 'I8': '5',
 'I9': '3'}

In [30]:
reduce_puzzle(grid_test_individual)

{'A1': '67',
 'A2': '167',
 'A3': '157',
 'A4': '2',
 'A5': '9',
 'A6': '4',
 'A7': '3',
 'A8': '8',
 'A9': '57',
 'B1': '23',
 'B2': '39',
 'B3': '259',
 'B4': '1',
 'B5': '7',
 'B6': '8',
 'B7': '6',
 'B8': '4',
 'B9': '259',
 'C1': '4',
 'C2': '8',
 'C3': '279',
 'C4': '3',
 'C5': '5',
 'C6': '6',
 'C7': '1',
 'C8': '29',
 'C9': '279',
 'D1': '26',
 'D2': '69',
 'D3': '4',
 'D4': '8',
 'D5': '3',
 'D6': '7',
 'D7': '5',
 'D8': '269',
 'D9': '1',
 'E1': '2368',
 'E2': '369',
 'E3': '289',
 'E4': '4',
 'E5': '1',
 'E6': '5',
 'E7': '7',
 'E8': '269',
 'E9': '29',
 'F1': '5',
 'F2': '17',
 'F3': '17',
 'F4': '6',
 'F5': '2',
 'F6': '9',
 'F7': '8',
 'F8': '3',
 'F9': '4',
 'G1': '9',
 'G2': '5',
 'G3': '3',
 'G4': '7',
 'G5': '8',
 'G6': '2',
 'G7': '4',
 'G8': '1',
 'G9': '6',
 'H1': '1',
 'H2': '2',
 'H3': '6',
 'H4': '5',
 'H5': '4',
 'H6': '3',
 'H7': '9',
 'H8': '7',
 'H9': '8',
 'I1': '78',
 'I2': '4',
 'I3': '78',
 'I4': '9',
 'I5': '6',
 'I6': '1',
 'I7': '2',
 'I8': '5',
 'I9': '3'}

In [31]:
solve_technique(test_individual,'single_position')

('Not solved',
 {'A1': '67',
  'A2': '167',
  'A3': '157',
  'A4': '2',
  'A5': '9',
  'A6': '4',
  'A7': '3',
  'A8': '8',
  'A9': '57',
  'B1': '23',
  'B2': '39',
  'B3': '259',
  'B4': '1',
  'B5': '7',
  'B6': '8',
  'B7': '6',
  'B8': '4',
  'B9': '259',
  'C1': '4',
  'C2': '8',
  'C3': '279',
  'C4': '3',
  'C5': '5',
  'C6': '6',
  'C7': '1',
  'C8': '29',
  'C9': '279',
  'D1': '26',
  'D2': '69',
  'D3': '4',
  'D4': '8',
  'D5': '3',
  'D6': '7',
  'D7': '5',
  'D8': '269',
  'D9': '1',
  'E1': '2368',
  'E2': '369',
  'E3': '289',
  'E4': '4',
  'E5': '1',
  'E6': '5',
  'E7': '7',
  'E8': '269',
  'E9': '29',
  'F1': '5',
  'F2': '17',
  'F3': '17',
  'F4': '6',
  'F5': '2',
  'F6': '9',
  'F7': '8',
  'F8': '3',
  'F9': '4',
  'G1': '9',
  'G2': '5',
  'G3': '3',
  'G4': '7',
  'G5': '8',
  'G6': '2',
  'G7': '4',
  'G8': '1',
  'G9': '6',
  'H1': '1',
  'H2': '2',
  'H3': '6',
  'H4': '5',
  'H5': '4',
  'H6': '3',
  'H7': '9',
  'H8': '7',
  'H9': '8',
  'I1': '78',
  'I2': '4',
  'I3': '78',
  'I4': '9',
  'I5': '6',
  'I6': '1',
  'I7': '2',
  'I8': '5',
  'I9': '3'},
 'Number of iterations made: 1')

In [32]:
solve_technique(test_individual,'single_candidate')

('Not solved',
 {'A1': '67',
  'A2': '167',
  'A3': '157',
  'A4': '2',
  'A5': '9',
  'A6': '4',
  'A7': '3',
  'A8': '8',
  'A9': '57',
  'B1': '23',
  'B2': '39',
  'B3': '259',
  'B4': '1',
  'B5': '7',
  'B6': '8',
  'B7': '6',
  'B8': '4',
  'B9': '259',
  'C1': '4',
  'C2': '8',
  'C3': '279',
  'C4': '3',
  'C5': '5',
  'C6': '6',
  'C7': '1',
  'C8': '29',
  'C9': '279',
  'D1': '26',
  'D2': '69',
  'D3': '4',
  'D4': '8',
  'D5': '3',
  'D6': '7',
  'D7': '5',
  'D8': '269',
  'D9': '1',
  'E1': '2368',
  'E2': '369',
  'E3': '289',
  'E4': '4',
  'E5': '1',
  'E6': '5',
  'E7': '7',
  'E8': '269',
  'E9': '29',
  'F1': '5',
  'F2': '17',
  'F3': '17',
  'F4': '6',
  'F5': '2',
  'F6': '9',
  'F7': '8',
  'F8': '3',
  'F9': '4',
  'G1': '9',
  'G2': '5',
  'G3': '3',
  'G4': '7',
  'G5': '8',
  'G6': '2',
  'G7': '4',
  'G8': '1',
  'G9': '6',
  'H1': '1',
  'H2': '2',
  'H3': '6',
  'H4': '5',
  'H5': '4',
  'H6': '3',
  'H7': '9',
  'H8': '7',
  'H9': '8',
  'I1': '78',
  'I2': '4',
  'I3': '78',
  'I4': '9',
  'I5': '6',
  'I6': '1',
  'I7': '2',
  'I8': '5',
  'I9': '3'},
 'Number of iterations made: 1')

In [33]:
solve_technique(test_individual,'naked_twins')

('Not solved',
 {'A1': '67',
  'A2': '167',
  'A3': '157',
  'A4': '2',
  'A5': '9',
  'A6': '4',
  'A7': '3',
  'A8': '8',
  'A9': '57',
  'B1': '23',
  'B2': '39',
  'B3': '259',
  'B4': '1',
  'B5': '7',
  'B6': '8',
  'B7': '6',
  'B8': '4',
  'B9': '259',
  'C1': '4',
  'C2': '8',
  'C3': '279',
  'C4': '3',
  'C5': '5',
  'C6': '6',
  'C7': '1',
  'C8': '29',
  'C9': '279',
  'D1': '26',
  'D2': '69',
  'D3': '4',
  'D4': '8',
  'D5': '3',
  'D6': '7',
  'D7': '5',
  'D8': '269',
  'D9': '1',
  'E1': '2368',
  'E2': '369',
  'E3': '289',
  'E4': '4',
  'E5': '1',
  'E6': '5',
  'E7': '7',
  'E8': '269',
  'E9': '29',
  'F1': '5',
  'F2': '17',
  'F3': '17',
  'F4': '6',
  'F5': '2',
  'F6': '9',
  'F7': '8',
  'F8': '3',
  'F9': '4',
  'G1': '9',
  'G2': '5',
  'G3': '3',
  'G4': '7',
  'G5': '8',
  'G6': '2',
  'G7': '4',
  'G8': '1',
  'G9': '6',
  'H1': '1',
  'H2': '2',
  'H3': '6',
  'H4': '5',
  'H5': '4',
  'H6': '3',
  'H7': '9',
  'H8': '7',
  'H9': '8',
  'I1': '78',
  'I2': '4',
  'I3': '78',
  'I4': '9',
  'I5': '6',
  'I6': '1',
  'I7': '2',
  'I8': '5',
  'I9': '3'},
 'Number of iterations made: 1')

In [34]:
solve_technique(test_individual,'naked_triple')

('Not solved',
 {'A1': '67',
  'A2': '167',
  'A3': '157',
  'A4': '2',
  'A5': '9',
  'A6': '4',
  'A7': '3',
  'A8': '8',
  'A9': '57',
  'B1': '23',
  'B2': '39',
  'B3': '259',
  'B4': '1',
  'B5': '7',
  'B6': '8',
  'B7': '6',
  'B8': '4',
  'B9': '259',
  'C1': '4',
  'C2': '8',
  'C3': '279',
  'C4': '3',
  'C5': '5',
  'C6': '6',
  'C7': '1',
  'C8': '29',
  'C9': '279',
  'D1': '26',
  'D2': '69',
  'D3': '4',
  'D4': '8',
  'D5': '3',
  'D6': '7',
  'D7': '5',
  'D8': '269',
  'D9': '1',
  'E1': '2368',
  'E2': '369',
  'E3': '289',
  'E4': '4',
  'E5': '1',
  'E6': '5',
  'E7': '7',
  'E8': '269',
  'E9': '29',
  'F1': '5',
  'F2': '17',
  'F3': '17',
  'F4': '6',
  'F5': '2',
  'F6': '9',
  'F7': '8',
  'F8': '3',
  'F9': '4',
  'G1': '9',
  'G2': '5',
  'G3': '3',
  'G4': '7',
  'G5': '8',
  'G6': '2',
  'G7': '4',
  'G8': '1',
  'G9': '6',
  'H1': '1',
  'H2': '2',
  'H3': '6',
  'H4': '5',
  'H5': '4',
  'H6': '3',
  'H7': '9',
  'H8': '7',
  'H9': '8',
  'I1': '78',
  'I2': '4',
  'I3': '78',
  'I4': '9',
  'I5': '6',
  'I6': '1',
  'I7': '2',
  'I8': '5',
  'I9': '3'},
 'Number of iterations made: 1')

### Testing solver with dataset

In [38]:
df = pd.read_csv('../Omega2020/data/dataset.csv').drop('Unnamed: 0', axis=1)
print(df.shape)
df.head()

(5030, 6)

,Id,Sudoku,Solution,Level,People,Average-Time
0,0,8...74...1.........7.5.9.4....65.4..73.....296...,8591742361648325973725698412916574837354186296...,Diabolical,254,25
1,1,.5.....7.9......6...21.75.8.4..69.3...8...4......,8539461729175823644621375981458692376283754197...,Moderate,281,12
2,2,...45.2..3.........8....4..7...94.3.9..5.2.76....,6974532183248617955819274637186945329435128762...,Diabolical,265,22
3,3,9......31.3...8.....5.7.9..3...4...8.916..54.4...,9274568316341982758153729643527496187916835424...,Tough,279,19
4,4,9.......2784.1.5.....4.....2.53.1.7...7...8......,9615387427846125395234796182953814761479568236...,Moderate,301,14

In [39]:
solve(df['Sudoku'][0])

(1,
 '859174236164832597372569841291657483735418629648293175926381754413725968587946312',
 '8...74...1.........7.5.9.4....65.4..73.....296.8.......2.3.1.5.........8...9....2',
 'Diabolical')

In [44]:
a = solve(df['Sudoku'][0])[2]

a = dict(zip(boxes, ["." if element == "." else element for element in a]))

In [45]:
# tranform a dictionary into a string
"".join([value if len(value) == 1 else "." for value in a.values()])

'8...74...1.........7.5.9.4....65.4..73.....296.8.......2.3.1.5.........8...9....2'

In [46]:
display(a)

8 . . |. 7 4 |. . .
1 . . |. . . |. . .
. 7 . |5 . 9 |. 4 .
------+------+------
. . . |6 5 . |4 . .
7 3 . |. . . |. 2 9
6 . 8 |. . . |. . .
------+------+------
. 2 . |3 . 1 |. 5 .
. . . |. . . |. . 8
. . . |9 . . |. . 2

In [48]:
df['Solver'] = df['Sudoku'].apply(lambda x: solve(x)[0])
df.head()

,Id,Sudoku,Solution,Level,People,Average-Time,Solver
0,0,8...74...1.........7.5.9.4....65.4..73.....296...,8591742361648325973725698412916574837354186296...,Diabolical,254,25,1
1,1,.5.....7.9......6...21.75.8.4..69.3...8...4......,8539461729175823644621375981458692376283754197...,Moderate,281,12,1
2,2,...45.2..3.........8....4..7...94.3.9..5.2.76....,6974532183248617955819274637186945329435128762...,Diabolical,265,22,1
3,3,9......31.3...8.....5.7.9..3...4...8.916..54.4...,9274568316341982758153729643527496187916835424...,Tough,279,19,1
4,4,9.......2784.1.5.....4.....2.53.1.7...7...8......,9615387427846125395234796182953814761479568236...,Moderate,301,14,1

In [49]:
df['Solver'].value_counts()

1    5030
Name: Solver, dtype: int64

### Testing solver by technique with dataset

In [50]:
df['Solved_single_position'] = df['Sudoku'].apply(lambda x: solve_technique(x, 'single_position')[0])
df['Solved_single_position'].value_counts()

Not solved    4813
Solved         217
Name: Solved_single_position, dtype: int64

In [51]:
df['Solved_single_candidate'] = df['Sudoku'].apply(lambda x: solve_technique(x, 'single_candidate')[0])
df['Solved_single_candidate'].value_counts()

Solved        2787
Not solved    2243
Name: Solved_single_candidate, dtype: int64

In [52]:
df['Solved_naked_twins']= df['Sudoku'].apply(lambda x: solve_technique(x, 'naked_twins')[0])
df['Solved_naked_twins'].value_counts()

Not solved    3658
Solved        1372
Name: Solved_naked_twins, dtype: int64

In [53]:
df['Solved_naked_triple']= df['Sudoku'].apply(lambda x: solve_technique(x, 'naked_triple')[0])
df['Solved_naked_triple'].value_counts()

Not solved    4790
Solved         240
Name: Solved_naked_triple, dtype: int64

In [54]:
df.head()

,Id,Sudoku,Solution,Level,People,Average-Time,Solver,Solved_single_position,Solved_single_candidate,Solved_naked_twins,Solved_naked_triple
0,0,8...74...1.........7.5.9.4....65.4..73.....296...,8591742361648325973725698412916574837354186296...,Diabolical,254,25,1,Not solved,Not solved,Not solved,Not solved
1,1,.5.....7.9......6...21.75.8.4..69.3...8...4......,8539461729175823644621375981458692376283754197...,Moderate,281,12,1,Not solved,Solved,Solved,Not solved
2,2,...45.2..3.........8....4..7...94.3.9..5.2.76....,6974532183248617955819274637186945329435128762...,Diabolical,265,22,1,Not solved,Not solved,Not solved,Not solved
3,3,9......31.3...8.....5.7.9..3...4...8.916..54.4...,9274568316341982758153729643527496187916835424...,Tough,279,19,1,Not solved,Not solved,Not solved,Not solved
4,4,9.......2784.1.5.....4.....2.53.1.7...7...8......,9615387427846125395234796182953814761479568236...,Moderate,301,14,1,Not solved,Solved,Solved,Not solved